### ISSUE TITLE
why ZoomStartupAnimation requires navController.view.layer.mask 

### ISSUE THREAD

**Issue by ramki1979** [Yalantis/FitTrack#1]
Is there any specific reason for `navController.view.layer.mask` existence in ZoomStartupAnimation.

**Comment by serejahh** [comment]
Hi @ramki1979. Thanks for your interest to our component!
I guess it animates heart image on startup. @Roman-Scherbakov, am I right?

**Comment by ramki1979** [comment]
Its looks like mask not required 
setting `maskBackgroundImageView.layer.position = navController.view.center` will work.

So just want to know is there anything I missed out here.
But thanks for the UI Interface component.

**Comment by serejahh** [comment]
Just a moment ago had a small talk with the author he said mask is really needed there. Also I tried to replace as you said and behavior is different. If you can replace it, PRs are welcome 😉

**Comment by ramki1979** [comment]
May be I am missing UI/UX design effect that is happening in ZoomStartupAnimation.

I assume that ZoomStartupAnimation task is to Zoomout the logo or do I am missing any vital Information related to UI/UX design here.

Below is the code for logo Zoomout effect, If ZoomStartupAnimation requirement is same as below then it makes sense to have a PR else it wouldn't make any sense.

I am using the ZoomOut effect in my next app, that is the reason I want to know the fine details related to its UI/UX design.

``` Swift
//  Applying background image to ViewController view
let bg = UIImage(imageLiteralResourceName: "bg")
view.layer.contents = bg.cgImage
view.layer.contentsScale = UIScreen.main().scale
view.layer.contentsGravity = "center"

//  Adding logo to the ViewController view
let logo = UIImage(imageLiteralResourceName: "logo")
let logoView = UIImageView(image: logo)
logoView.layer.position = view.center
self.view.addSubview(logoView)

//  logo, Zoomout animation
UIView.animate(withDuration: 0.3, delay: 1, options: .curveLinear,
                       animations: {
                        logoView.transform = CGAffineTransform(scaleX: 10, y: 10)
                        logoView.alpha = 0
            },
                       completion: { _ in
                        logoView.removeFromSuperview()
        })

```
