### ISSUE TITLE
Update project for swift 3

### ISSUE THREAD

**Issue by HieuLsw** [Yalantis/FitTrack#2]
Hi Yalantis. The first i wanna tks you for your awesome work. Can you convert project to swift 3( pod for swift 3, example project for swift 3 ). :)

**Comment by Vodolazkyi** [comment]
Yes, Thank you for your feedback !

**Comment by rnkyr** [comment]
Hey, @HieuLsw!
Sorry for the late reaction. Please let us know if you're still interested in updates. Probable to current swift's version
